
index_gdrive:
	go run *.go -id gdrive "/Volumes/GoogleDrive/Meine Ablage"

on_download:
	go run *.go -out ./test-fileindex.json -id test ~/Downloads

index_mdbackup:
	go run *.go -out ./mdbackup-fileindex.json -id mdbackup_ssd "/Volumes/MD Backup/Backups/BackupPrivate"